const testRoute = require("./test.route");
const authRoutes = require("./auth.route");
const userRoutes = require("./user.route");
const customerConsolationRoute = require("./customer-consolation.route");
const wardRoutes = require("./ward.route");
const typeOfPersonRoutes = require("./type-of-person.route");
const invoiceRoutes = require("./invoice.route");
const departPlaceRoutes = require("./depart-place.route");
const tourRoutes = require("./tour.route");
const filterRoutes = require("./filter.route");
const provinceRoutes = require("./province.route");
const vehicleRoutes = require("./vehicle.route");
const tourCategoryRoutes = require("./tour-category.route");
const newsRoutes = require("./news.route");
const newsCategoryRoutes = require("./news-category.route");
const userFavoriteRoutes = require("./user-favorite.route");
const userSaveRoutes = require("./user-save.route");
const userShareRoutes = require("./user-share.route");
const commentRoutes = require("./comment.route");
const shortRoutes = require("./short.route");
const galleryRoutes = require("./gallery.route");
const galleryCategoryRoutes = require("./gallery-category.route");
const chatRoutes = require("./chat.route");
const messageRoutes = require("./message.route");
const siteConfigRoutes = require("./site-config.route");
const supportMessageRoutes = require("./support.route");
const flightRoutes = require("./flight.route");
const friendRoutes = require("./friend.route");
const conversationRoutes = require("./conversation.route");
const groupChatRoutes = require("./group-chat.route");
const cccdRoutes = require("./cccd.routes");
module.exports = (app) => {
  const version = "/api/v1";
  app.use(version, testRoute);

  app.use(version, customerConsolationRoute);

  app.use(version + "/auth", authRoutes);
  app.use(version + "/cccd", cccdRoutes);
  app.use(version + "/type-of-person", typeOfPersonRoutes);
  app.use(version + "/invoice", invoiceRoutes);
  app.use(version + "/tours", tourRoutes);
  app.use(version + "/depart-place", departPlaceRoutes);
  app.use(version + "/filter", filterRoutes);
  app.use(version + "/province", provinceRoutes);

  app.use(version + "/tour-category", tourCategoryRoutes);
  app.use(version + "/news", newsRoutes);
  app.use(version + "/news-category", newsCategoryRoutes);

  app.use(version + "/comments", commentRoutes);
  app.use(version + "/shorts", shortRoutes);
  app.use(version + "/gallery", galleryRoutes);
  app.use(version + "/gallery-category", galleryCategoryRoutes);
  app.use(version + "/chat", chatRoutes);
  app.use(version + "/message", messageRoutes);
  app.use(version + "/site-config", siteConfigRoutes);
  app.use(version + "/support", supportMessageRoutes);
  app.use(version + "/flight", flightRoutes);
  app.use(version + "/friends", friendRoutes);
  app.use(version + "/conversation", conversationRoutes);
  app.use(version + "/group-chat", groupChatRoutes);
  app.use(version + "/user-favorite", userFavoriteRoutes);
  app.use(version + "/user-saves", userSaveRoutes);
  app.use(version + "/user-shares", userShareRoutes);
  app.use(version + "/users", userRoutes);
  app.use(version + "/vehicles", vehicleRoutes);
  app.use(version + "/wards", wardRoutes);
};
