const testRoute = require("./test.route");
const userRoute = require("./user.route");
const customerConsolationRoute = require("./customer-consolation.route");
const wardRoute = require("./ward.route");
const typeOfPersonRoute = require("./type-of-person.route");
const invoiceRoute = require("./invoice.route");
const departPlace = require("./depart-place.route");
const tourRoutes = require("./tour.route");
const filterRoutes = require("./filter.route");
const vehicleRoutes = require("./vehicle.route");
const tourCategoryRoutes = require("./tour-category.route");
const newsRoute = require("./news.route");
const newsCategoryRoute = require("./news-category.route");
const userFavorite = require("./user-favorite.route");
const userSave = require("./user-save.route");
const userShare = require("./user-share.route");
module.exports = (app) => {
  const version = "/api/v1";
  app.use(version, testRoute);
  app.use(version + "/user", userRoute);
  app.use(version, customerConsolationRoute);
  app.use(version + "/wards", wardRoute);
  app.use(version + "/type-of-person", typeOfPersonRoute);
  app.use(version + "/invoice", invoiceRoute);
  app.use(version + "/tours", tourRoutes);
  app.use(version + "/depart-place", departPlace);
  app.use(version + "/filter", filterRoutes);
  app.use(version + "/vehicle", vehicleRoutes);
  app.use(version + "/tour-category", tourCategoryRoutes);
  app.use(version + "/news", newsRoute);
  app.use(version + "/news-category", newsCategoryRoute);
  app.use(version + "/user-favorite", userFavorite);
  app.use(version + "/user-save", userSave);
  app.use(version + "/user-share", userShare);
};
