const express = require("express");
const router = express.Router();
const controller = require("../../controllers/client/invoice.controller");
router.post("/payUsingCash", controller.createInvoice);
router.post("/pay-with-momo", controller.payWithMomo);
router.post("/momo-ipn", controller.momoIPN);
router.get("/detail/:invoiceId", controller.getById);
router.get("/code/:invoiceCode", controller.getByCode);
router.get("/send-email/:invoiceId", controller.sendInvoiceEmail);
router.get("/get-all-invoice", controller.getInvoices);
module.exports = router;
