const express = require("express");
const router = express.Router();
const controller = require("../../controllers/client/invoice.controller");
const { checkAuth } = require("../../../../middlewares/auth.middleware");
router.post("/payUsingCash", checkAuth, controller.createInvoice);
router.post("/pay-with-momo", checkAuth, controller.payWithMomo);
router.post("/momo-ipn", controller.momoIPN);
router.get("/detail/:invoiceId", controller.getById);
router.get("/code/:invoiceCode", controller.getByCode);
router.get("/send-email/:invoiceId", controller.sendInvoiceEmail);
router.get("/get-all-invoice", controller.getInvoices);
router.patch("/cancel/:id", controller.userCancelInvoice);
module.exports = router;
