const express = require("express");
const router = express.Router();
const controller = require("../../controllers/client/message.controller");
const { checkAuth } = require("../../../../middlewares/auth.middleware");
router.get("/get-messages/:chatId", checkAuth, controller.getMessages);
router.post("/send-message/:chatId", checkAuth, controller.sendMessage);
router.delete("/delete/:messageId", checkAuth, controller.deleteMessage);
router.patch("/react/:messageId", checkAuth, controller.reactMessage);
router.patch("/edit/:messageId", checkAuth, controller.editMessage);
router.post("/mark-read/:chatId", checkAuth, controller.markAsRead);
module.exports = router;
