const tourCategoryRoute = require("../admin/tour-category.route");
const travelTimeRoute = require("../admin/travel-time.route");
const hotelRoute = require("../admin/hotel.route");
const termRoute = require("../admin/term.route");
const vehicleRoute = require("../admin/vehicle.route");
const frequencyRoute = require("../admin/frequency.route");
const tourRoute = require("./tour.route");
const typeOfPersonRoute = require("./type-of-person.route");
const filterRoute = require("./filter.route");
const adminRoute = require("./admin.route");
module.exports = (app) => {
  const version = "/api/v1/admin";
  app.use(version + "/tour-categories", tourCategoryRoute);
  app.use(version + "/travel-time", travelTimeRoute);
  app.use(version + "/hotel", hotelRoute);
  app.use(version + "/term", termRoute);
  app.use(version + "/vehicle", vehicleRoute);
  app.use(version + "/frequency", frequencyRoute);
  app.use(version + "/tours", tourRoute);
  app.use(version + "/type-of-person", typeOfPersonRoute);
  app.use(version + "/filter", filterRoute);
  app.use(version, adminRoute);
};
