const express = require("express");
const router = express.Router();
const controller = require("../../controllers/admin/tour.controller");
const validate = require("../../../../validates/admin/tour.validate");
router.get("/tour", controller.getTours);
router.patch("/tour/bulk-update", controller.bulkUpdateTours);
router.patch("/tour/:id", controller.updateTour);
router.post("/create", validate.validateCreateTour, controller.createTour);
router.post("/check-info-tour-create", controller.checkTour);
module.exports = router;
